import telebot
bot = telebot.TeleBot('1323964128:AAF37zB6zMesZbv_JK8KnmHmCCyJL6B0fBg')
import sqlite3

conn = sqlite3.connect('//home//Anastasia56547657//bot.db')
cursor = conn.cursor()

from telebot import types


keyboard1 = telebot.types.ReplyKeyboardMarkup(True,True)
keyboard1.row('греческий гороскоп','восточный гороскоп','тибетский гороскоп')
keyboard1.row('зодиакальный гороскоп',' кельский гороскоп')


@bot.message_handler(commands=['start'])
def start_message(message):
    bot.send_message(message.chat.id, 'Привет, выбери тип гороскопа?', reply_markup=keyboard1)

@bot.message_handler(content_types=['text'])
def send_text(message):
    if message.text.lower() == 'зодиакальный гороскоп':
        keyboard = types.InlineKeyboardMarkup()
        key_oven = types.InlineKeyboardButton(text='21.03-20.04',  callback_data='zodiac Овен')
        keyboard.add(key_oven)
        key_telec = types.InlineKeyboardButton(text='21.04-21.05', callback_data='zodiac Телец')
        keyboard.add(key_telec)
        key_bliznecy = types.InlineKeyboardButton(text='22.05-21.06', callback_data='zodiac Близнецы')
        keyboard.add(key_bliznecy)
        key_rak = types.InlineKeyboardButton(text='22.06-22.07', callback_data='zodiac Рак')
        keyboard.add(key_rak)
        key_lev = types.InlineKeyboardButton(text='23.07-23.08', callback_data='zodiac Лев')
        keyboard.add(key_lev)
        key_deva = types.InlineKeyboardButton(text='24.08-23.09', callback_data='zodiac Дева')
        keyboard.add(key_deva)
        key_vesy = types.InlineKeyboardButton(text='24.09-23.10', callback_data='zodiac Весы')
        keyboard.add(key_vesy)
        key_scorpion = types.InlineKeyboardButton(text='24.10-22.11', callback_data='zodiac Скорпион')
        keyboard.add(key_scorpion)
        key_strelec = types.InlineKeyboardButton(text='23.11-22.12', callback_data='zodiac Стрелец')
        keyboard.add(key_strelec)
        key_kozerog = types.InlineKeyboardButton(text='23.12-20.01', callback_data='zodiac Козерог')
        keyboard.add(key_kozerog)
        key_vodoley = types.InlineKeyboardButton(text='21.01-19.02', callback_data='zodiac Водолей')
        keyboard.add(key_vodoley)
        key_ryby = types.InlineKeyboardButton(text='20.02-20.03', callback_data='zodiac Рыбы')
        keyboard.add(key_ryby)
        bot.send_message(message.from_user.id, text='Выбери свою дату рождения', reply_markup=keyboard)

    elif message.text.lower() == 'кельский гороскоп':
        keyboard = types.InlineKeyboardMarkup()
        key_olen = types.InlineKeyboardButton(text='24.12-20.01',  callback_data='zodiac Олень')
        keyboard.add(key_olen)
        key_kot = types.InlineKeyboardButton(text='21.01-17.02', callback_data='zodiac Кот')
        keyboard.add(key_kot)
        key_zmeya = types.InlineKeyboardButton(text='18.02-17.03', callback_data='zodiac Змея')
        keyboard.add(key_zmeya)
        key_lisa = types.InlineKeyboardButton(text='18.03-14.04', callback_data='zodiac Лиса')
        keyboard.add(key_lisa)
        key_korova = types.InlineKeyboardButton(text='15.04-12.05', callback_data='zodiac Корова')
        keyboard.add(key_korova)
        key_mrkn = types.InlineKeyboardButton(text='13.05-09.06', callback_data='zodiac Морской_конек')
        keyboard.add(key_mrkn)
        key_korolek = types.InlineKeyboardButton(text='10.06-07.07', callback_data='zodiac Королек')
        keyboard.add(key_korolek)
        key_loshad = types.InlineKeyboardButton(text='08.07-04.08', callback_data='zodiac Лошадь')
        keyboard.add(key_loshad)
        key_losoc = types.InlineKeyboardButton(text='05.08-01.09', callback_data='zodiac Лосось')
        keyboard.add(key_losoc)
        key_lebed = types.InlineKeyboardButton(text='02.09-29.09', callback_data='zodiac Лебедь')
        keyboard.add(key_lebed)
        key_babochka = types.InlineKeyboardButton(text='30.09-27.10', callback_data='zodiac Бабочка')
        keyboard.add(key_babochka)
        key_volk = types.InlineKeyboardButton(text='28.10-24.11', callback_data='zodiac Волк')
        keyboard.add(key_volk)
        key_sokol = types.InlineKeyboardButton(text='25.11-23.12', callback_data='zodiac Сокол')
        keyboard.add(key_sokol)
        bot.send_message(message.from_user.id, text='Выбери свою дату рождения', reply_markup=keyboard)

    elif message.text.lower() == 'греческий гороскоп':
        keyboard = types.InlineKeyboardMarkup()
        key_afina = types.InlineKeyboardButton(text='21.03-20.04',  callback_data='zodiac Афина')
        keyboard.add(key_afina)
        key_afrodita = types.InlineKeyboardButton(text='21.04-20.05', callback_data='zodiac Афродита')
        keyboard.add(key_afrodita)
        key_apollon = types.InlineKeyboardButton(text='21.05-21.06', callback_data='zodiac Аполлон')
        keyboard.add(key_apollon)
        key_germec = types.InlineKeyboardButton(text='22.06-22.07', callback_data='zodiac Гермес')
        keyboard.add(key_germec)
        key_cevs = types.InlineKeyboardButton(text='23.07-23.08', callback_data='zodiac Зевс')
        keyboard.add(key_cevs)
        key_demetra = types.InlineKeyboardButton(text='24.08-23.09', callback_data='zodiac Деметра')
        keyboard.add(key_demetra)
        key_gefest = types.InlineKeyboardButton(text='24.09-23.10', callback_data='zodiac Гефест')
        keyboard.add(key_gefest)
        key_ares = types.InlineKeyboardButton(text='24.10-22.11', callback_data='zodiac Арес')
        keyboard.add(key_ares)
        key_artemida = types.InlineKeyboardButton(text='23.11-21.12', callback_data='zodiac Артемида')
        keyboard.add(key_artemida)
        key_gestia = types.InlineKeyboardButton(text='22.12-20.01', callback_data='zodiac Гестия')
        keyboard.add(key_gestia)
        key_gera = types.InlineKeyboardButton(text='21.01-19.02', callback_data='zodiac Гера')
        keyboard.add(key_gera)
        key_pocedon= types.InlineKeyboardButton(text='20.12-20.04', callback_data='zodiac Посейдон')
        keyboard.add(key_pocedon)
        bot.send_message(message.from_user.id, text='Выбери свою дату рождения', reply_markup=keyboard)

    elif message.text.lower() == 'тибетский гороскоп':
        keyboard = types.InlineKeyboardMarkup()
        key_zveu = types.InlineKeyboardButton(text='1940, 1952, 1964, 1976,1988, 2000, 2012',  callback_data='zodiac Змей')
        keyboard.add(key_zveu)
        key_kobra = types.InlineKeyboardButton(text='1941, 1953, 1965, 1977,1989, 2001, 2013', callback_data='zodiac Кобра')
        keyboard.add(key_kobra)
        key_phogn = types.InlineKeyboardButton(text='1942, 1954, 1966, 1978,1990, 2002, 2014', callback_data='zodiac Хранитель')
        keyboard.add(key_phogn)
        key_istochnik = types.InlineKeyboardButton(text='1943, 1955, 1967, 1979,1991, 2003, 2015', callback_data='zodiac Источник')
        keyboard.add(key_istochnik)
        key_kolona = types.InlineKeyboardButton(text='1944, 1956, 1968, 1980,1992, 2004, 2016', callback_data='zodiac Колонна')
        keyboard.add(key_kolona)
        key_gong = types.InlineKeyboardButton(text='1945, 1957, 1969, 1981,1993, 2005, 2017', callback_data='zodiac Гонг')
        keyboard.add(key_gong)
        key_cherepaha = types.InlineKeyboardButton(text='1946, 1958, 1970, 1982,1994, 2006, 2018', callback_data='zodiac Черепаха')
        keyboard.add(key_cherepaha)
        key_braclet = types.InlineKeyboardButton(text='1947, 1959, 1971, 1983,1995, 2007, 2019', callback_data='zodiac Браслет')
        keyboard.add(key_braclet)
        key_byivol = types.InlineKeyboardButton(text='1948, 1960, 1972, 1984,1996, 2008, 2020', callback_data='zodiac Буйвол')
        keyboard.add(key_byivol)
        key_luna = types.InlineKeyboardButton(text='1949, 1961, 1973, 1985,1997, 2009, 2021', callback_data='zodiac Луна')
        keyboard.add(key_luna)
        key_sun = types.InlineKeyboardButton(text='1950, 1962, 1974, 1986,1998, 2010', callback_data='zodiac Солнце')
        keyboard.add(key_sun)
        key_monaph = types.InlineKeyboardButton(text='1951, 1963, 1975, 1987,1999, 2011', callback_data='zodiac Монах')
        keyboard.add(key_monaph)
        bot.send_message(message.from_user.id, text='Выбери свой год рождения', reply_markup=keyboard)

    elif message.text.lower() == 'восточный гороскоп':
        keyboard = types.InlineKeyboardMarkup()
        key_drakon = types.InlineKeyboardButton(text='1940, 1952, 1964, 1976,1988, 2000, 2012',  callback_data='zodiac Дракон')
        keyboard.add(key_drakon)
        key_zmeya = types.InlineKeyboardButton(text='1941, 1953, 1965, 1977,1989, 2001, 2013', callback_data='zodiac Змеяя')
        keyboard.add(key_zmeya)
        key_horse = types.InlineKeyboardButton(text='1942, 1954, 1966, 1978,1990, 2002, 2014', callback_data='zodiac Лошадьь')
        keyboard.add(key_horse)
        key_koza = types.InlineKeyboardButton(text='1943, 1955, 1967, 1979,1991, 2003, 2015', callback_data='zodiac Коза')
        keyboard.add(key_koza)
        key_obez = types.InlineKeyboardButton(text='1944, 1956, 1968, 1980,1992, 2004, 2016', callback_data='zodiac Обезьяна')
        keyboard.add(key_obez)
        key_petuh = types.InlineKeyboardButton(text='1945, 1957, 1969, 1981,1993, 2005, 2017', callback_data='zodiac Петух')
        keyboard.add(key_petuh)
        key_dog = types.InlineKeyboardButton(text='1946, 1958, 1970, 1982,1994, 2006, 2018', callback_data='zodiac Собака')
        keyboard.add(key_dog)
        key_pig = types.InlineKeyboardButton(text='1947, 1959, 1971, 1983,1995, 2007, 2019', callback_data='zodiac Свинья')
        keyboard.add(key_pig)
        key_krus = types.InlineKeyboardButton(text='1948, 1960, 1972, 1984,1996, 2008, 2020', callback_data='zodiac Крыса')
        keyboard.add(key_krus)
        key_buk = types.InlineKeyboardButton(text='1949, 1961, 1973, 1985,1997, 2009, 2021', callback_data='zodiac Бык')
        keyboard.add(key_buk)
        key_tigr = types.InlineKeyboardButton(text='1950, 1962, 1974, 1986,1998, 2010', callback_data='zodiac Тигр')
        keyboard.add(key_tigr)
        key_rabbit = types.InlineKeyboardButton(text='1951, 1963, 1975, 1987,1999, 2011', callback_data='zodiac Кролик')
        keyboard.add(key_rabbit)
        bot.send_message(message.from_user.id, text='Выбери свой год рождения', reply_markup=keyboard)

@bot.callback_query_handler(func = lambda call: True)
def callback_worker(call):
    data = call.data.split(" ")
    command = data[0]
    sign = data[1]
    if command == "zodiac":
                with sqlite3.connect('//home//Anastasia56547657//bot.db') as connection:
                    cursor = connection.cursor()
                    cursor.execute("SELECT prediction FROM horoscope WHERE `zodiac sign` = (?)", [sign])
                    data = cursor.fetchone()
                    bot.send_message(call.from_user.id, 'Твой гороскоп:')
                    bot.send_message(call.from_user.id, data)



bot.polling(none_stop=True)
conn.close()

